
import { useState } from "react";
import type { ScreenplaySettings } from "../types";

const TABS = ["General", "Elements", "Scene Numbers", "Page Numbers", "Dialogue", "Pagination", "Revisions", "Production", "Export"] as const;
type Tab = typeof TABS[number];

export function ScreenplaySettingsDialog({ initial, onSave, onClose }: { initial: ScreenplaySettings; onSave(value: ScreenplaySettings): void; onClose(): void }) {
  const [value, setValue] = useState(() => structuredClone(initial));
  const [tab, setTab] = useState<Tab>("General");
  const patch = (section: Exclude<keyof ScreenplaySettings, "preset">, next: object) => setValue((current) => ({ ...current, [section]: { ...(current[section] as object), ...next } }));
  const check = (label: string, checked: boolean, change: (checked: boolean) => void, disabled = false) => <label className="check-label"><input type="checkbox" checked={checked} disabled={disabled} onChange={(event) => change(event.target.checked)}/><span>{label}</span></label>;

  return <div className="settings-backdrop" onMouseDown={onClose}><section className="screenplay-settings-dialog" role="dialog" aria-modal="true" aria-label="Screenplay Settings" onMouseDown={(event) => event.stopPropagation()}>
    <header><div><p className="eyebrow">Project settings</p><h2>Screenplay Settings</h2></div><button className="icon-button" aria-label="Close screenplay settings" onClick={onClose}>Ã—</button></header>
    <div className="screenplay-settings-body"><nav aria-label="Screenplay settings sections">{TABS.map((item) => <button key={item} className={tab === item ? "active" : ""} onClick={() => setTab(item)}>{item}</button>)}</nav>
      <div className="screenplay-settings-panel">
        {tab === "General" && <><h3>Screenplay preset</h3><label>Preset<select value={value.preset} onChange={(event) => setValue({ ...value, preset: event.target.value as ScreenplaySettings["preset"] })}><option value="spec-script">Spec Script</option><option value="shooting-script">Shooting Script</option><option value="uk-screenplay">UK Screenplay</option><option value="us-screenplay">US Screenplay</option><option value="custom">Custom</option></select></label><p className="setting-help">Presets establish safe defaults. Individual controls remain editable per project.</p></>}
        {tab === "Elements" && <><h3>Element formatting</h3><p className="setting-help">Olukotan applies the selected screenplay preset to headings, action, characters, dialogue, transitions, and shots while preserving explicit element choices.</p></>}
        {tab === "Scene Numbers" && <><h3>Scene numbers</h3>{check("Show Scene Numbers", value.sceneNumbers.enabled, (enabled) => patch("sceneNumbers", { enabled }))}<label>Numbering mode<select value={value.sceneNumbers.mode} onChange={(event) => patch("sceneNumbers", { mode: event.target.value as ScreenplaySettings["sceneNumbers"]["mode"] })}><option value="automatic">Automatic</option><option value="manual">Manual</option><option value="locked">Locked Production Numbers</option></select></label><label>Start at<input min="1" type="number" value={value.sceneNumbers.startAt} onChange={(event) => patch("sceneNumbers", { startAt: Math.max(1, Number(event.target.value) || 1) })}/></label><label>Position<select value={value.sceneNumbers.position} onChange={(event) => patch("sceneNumbers", { position: event.target.value as ScreenplaySettings["sceneNumbers"]["position"] })}><option value="both">Both sides</option><option value="left">Left</option><option value="right">Right</option></select></label>{check("Show in editor", value.sceneNumbers.showInEditor, (showInEditor) => patch("sceneNumbers", { showInEditor }))}{check("Show in export", value.sceneNumbers.showInExport, (showInExport) => patch("sceneNumbers", { showInExport }))}{check("Show in print", value.sceneNumbers.showInPrint, (showInPrint) => patch("sceneNumbers", { showInPrint }))}</>}
        {tab === "Page Numbers" && <><h3>Page numbers</h3>{check("Show Page Numbers", value.pageNumbers.enabled, (enabled) => patch("pageNumbers", { enabled }))}<label>Position<select value={value.pageNumbers.position} onChange={(event) => patch("pageNumbers", { position: event.target.value as ScreenplaySettings["pageNumbers"]["position"] })}><option value="top-right">Top Right</option><option value="top-centre">Top Centre</option><option value="bottom-right">Bottom Right</option></select></label><label>Start displaying<select value={String(value.pageNumbers.startOnPage)} onChange={(event) => patch("pageNumbers", { startOnPage: event.target.value === "custom" ? "custom" : Number(event.target.value) as 1 | 2 })}><option value="1">Page 1</option><option value="2">Page 2</option><option value="custom">Custom page</option></select></label>{value.pageNumbers.startOnPage === "custom" && <label>Custom start page<input min="1" type="number" value={value.pageNumbers.customStartPage} onChange={(event) => patch("pageNumbers", { customStartPage: Math.max(1, Number(event.target.value) || 1) })}/></label>}<label>First visible number<input min="1" type="number" value={value.pageNumbers.firstVisibleNumber} onChange={(event) => patch("pageNumbers", { firstVisibleNumber: Math.max(1, Number(event.target.value) || 1) })}/></label>{check("Hide number on first page", value.pageNumbers.hideOnFirstPage, (hideOnFirstPage) => patch("pageNumbers", { hideOnFirstPage }))}</>}
        {tab === "Dialogue" && <><h3>Character continueds</h3><label>Character CONT'D<select value={value.continueds.character} onChange={(event) => patch("continueds", { character: event.target.value as ScreenplaySettings["continueds"]["character"] })}><option value="automatic">Automatic</option><option value="manual">Manual</option><option value="off">Off</option></select></label>{check("Show (MORE) across pages", value.continueds.dialogueMore, (dialogueMore) => patch("continueds", { dialogueMore }))}{check("Show Character (CONT'D) on next page", value.continueds.dialogueContinued, (dialogueContinued) => patch("continueds", { dialogueContinued }))}</>}
        {tab === "Pagination" && <><h3>Pagination</h3><label>View mode<select value={value.pagination.viewMode} onChange={(event) => patch("pagination", { viewMode: event.target.value as ScreenplaySettings["pagination"]["viewMode"] })}><option value="page">Page View</option><option value="continuous">Continuous View</option></select></label><label>Page size<select value={value.pagination.pageSize} onChange={(event) => patch("pagination", { pageSize: event.target.value as ScreenplaySettings["pagination"]["pageSize"] })}><option>A4</option><option>US Letter</option></select></label></>}
        {tab === "Revisions" && <><h3>Revisions</h3>{check("Revision Mode", value.revisions.enabled, (enabled) => patch("revisions", { enabled }))}<p className="setting-help">Revision-set marks are retained as project metadata. Export controls remain disabled until marks can be rendered faithfully.</p></>}
        {tab === "Production" && <><h3>Production</h3><p className="setting-help">Use the Production menu to number, renumber, lock, unlock, remove, or set the current scene number. Locked scenes preserve production references when scenes are inserted or reordered.</p></>}
        {tab === "Export" && <><h3>Export defaults</h3><label>Default format<select value={value.exportDefaults.format} onChange={(event) => patch("exportDefaults", { format: event.target.value as ScreenplaySettings["exportDefaults"]["format"] })}><option value="pdf">PDF</option><option value="fdx">Final Draft XML</option><option value="docx">Word document</option><option value="rtf">Rich Text Format</option><option value="fountain">Fountain</option><option value="txt">Plain text</option><option value="md">Markdown</option><option value="html">HTML</option></select></label>{check("Include title page", value.exportDefaults.includeTitlePage, (includeTitlePage) => patch("exportDefaults", { includeTitlePage }))}{check("Include scene numbers", value.exportDefaults.includeSceneNumbers, (includeSceneNumbers) => patch("exportDefaults", { includeSceneNumbers }))}{check("Include page numbers", value.exportDefaults.includePageNumbers, (includePageNumbers) => patch("exportDefaults", { includePageNumbers }))}{check("Include script notes when supported", value.exportDefaults.includeScriptNotes, (includeScriptNotes) => patch("exportDefaults", { includeScriptNotes }))}{check("Include revision marks when supported", value.exportDefaults.includeRevisionMarks, (includeRevisionMarks) => patch("exportDefaults", { includeRevisionMarks }), true)}{check("Include omitted scenes", value.exportDefaults.includeOmittedScenes, (includeOmittedScenes) => patch("exportDefaults", { includeOmittedScenes }))}</>}
      </div>
    </div><footer><button className="secondary" onClick={onClose}>Cancel</button><button className="primary" onClick={() => onSave(value)}>Save screenplay settings</button></footer>
  </section></div>;
}

