import { useState } from "react";
import type { ScreenplaySettings } from "../types";

const TABS = ["General", "Elements", "Scene Numbers", "Page Numbers", "Dialogue", "Pagination", "Revisions", "Production", "Title Page", "Export"] as const;
type Tab = typeof TABS[number];

export function ScreenplaySettingsDialog({ initial, onSave, onClose }: {
  initial: ScreenplaySettings;
  onSave(value: ScreenplaySettings): void;
  onClose(): void;
}) {
  const [value, setValue] = useState(() => structuredClone(initial));
  const [tab, setTab] = useState<Tab>("General");
  const patch = (section: Exclude<keyof ScreenplaySettings, "preset">, next: object) =>
    setValue((current) => ({ ...current, [section]: { ...(current[section] as object), ...next } }));

  return <div className="settings-backdrop" onMouseDown={onClose}>
    <section className="screenplay-settings-dialog" role="dialog" aria-modal="true" aria-label="Screenplay Settings" onMouseDown={(event) => event.stopPropagation()}>
      <header><div><p className="eyebrow">Project settings</p><h2>Screenplay Settings</h2></div><button className="icon-button" aria-label="Close screenplay settings" onClick={onClose}>×</button></header>
      <div className="screenplay-settings-body">
        <nav aria-label="Screenplay settings sections">{TABS.map((item) => <button key={item} className={tab === item ? "active" : ""} onClick={() => setTab(item)}>{item}</button>)}</nav>
        <div className="screenplay-settings-panel">
          {tab === "General" && <><h3>Screenplay preset</h3><label>Preset<select value={value.preset} onChange={(event) => setValue({ ...value, preset: event.target.value as ScreenplaySettings["preset"] })}><option value="spec-script">Spec Script</option><option value="shooting-script">Shooting Script</option><option value="uk-screenplay">UK Screenplay</option><option value="us-screenplay">US Screenplay</option><option value="custom">Custom</option></select></label><p className="setting-help">Presets establish safe defaults. Individual controls remain editable per project.</p></>}
          {tab === "Scene Numbers" && <><h3>Scene numbers</h3><label className="check-label"><input type="checkbox" checked={value.sceneNumbers.enabled} onChange={(event) => patch("sceneNumbers", { enabled: event.target.checked })}/><span>Show Scene Numbers</span></label><label>Numbering mode<select value={value.sceneNumbers.mode} onChange={(event) => patch("sceneNumbers", { mode: event.target.value as ScreenplaySettings["sceneNumbers"]["mode"] })}><option value="automatic">Automatic</option><option value="manual">Manual</option><option value="locked">Locked Production Numbers</option></select></label><label>Position<select value={value.sceneNumbers.position} onChange={(event) => patch("sceneNumbers", { position: event.target.value as ScreenplaySettings["sceneNumbers"]["position"] })}><option value="both">Both sides</option><option value="left">Left</option><option value="right">Right</option></select></label><label className="check-label"><input type="checkbox" checked={value.sceneNumbers.showInEditor} onChange={(event) => patch("sceneNumbers", { showInEditor: event.target.checked })}/><span>Show in editor</span></label><label className="check-label"><input type="checkbox" checked={value.sceneNumbers.showInExport} onChange={(event) => patch("sceneNumbers", { showInExport: event.target.checked })}/><span>Show in PDF export</span></label><label className="check-label"><input type="checkbox" checked={value.sceneNumbers.showInPrint} onChange={(event) => patch("sceneNumbers", { showInPrint: event.target.checked })}/><span>Show in printed screenplay</span></label></>}
          {tab === "Page Numbers" && <><h3>Page-number foundation</h3><label className="check-label"><input type="checkbox" checked={value.pageNumbers.enabled} onChange={(event) => patch("pageNumbers", { enabled: event.target.checked })}/><span>Show Page Numbers</span></label><label>Position<select value={value.pageNumbers.position} onChange={(event) => patch("pageNumbers", { position: event.target.value as ScreenplaySettings["pageNumbers"]["position"] })}><option value="top-right">Top Right</option><option value="top-centre">Top Centre</option><option value="bottom-right">Bottom Right</option></select></label><label>Start displaying<select value={String(value.pageNumbers.startOnPage)} onChange={(event) => patch("pageNumbers", { startOnPage: event.target.value === "custom" ? "custom" : Number(event.target.value) as 1 | 2 })}><option value="1">Page 1</option><option value="2">Page 2</option><option value="custom">Custom page</option></select></label><p className="setting-help">These values are stored now. Exact page-number rendering will activate with the font-metric pagination engine.</p></>}
          {tab === "Dialogue" && <><h3>Character continueds</h3><label>Character CONT'D<select value={value.continueds.character} onChange={(event) => patch("continueds", { character: event.target.value as ScreenplaySettings["continueds"]["character"] })}><option value="automatic">Automatic</option><option value="manual">Manual</option><option value="off">Off</option></select></label><label className="check-label"><input type="checkbox" checked={value.continueds.dialogueMore} onChange={(event) => patch("continueds", { dialogueMore: event.target.checked })}/><span>Show (MORE) across pages</span></label><label className="check-label"><input type="checkbox" checked={value.continueds.dialogueContinued} onChange={(event) => patch("continueds", { dialogueContinued: event.target.checked })}/><span>Show Character (CONT'D) on next page</span></label><p className="setting-help">Automatic character continueds are active. Page-break markers wait for exact pagination.</p></>}
          {tab === "Pagination" && <><h3>Pagination</h3><label>View mode<select value={value.pagination.viewMode} onChange={(event) => patch("pagination", { viewMode: event.target.value as ScreenplaySettings["pagination"]["viewMode"] })}><option value="page">Page View</option><option value="continuous">Continuous View</option></select></label><label>Page size<select value={value.pagination.pageSize} onChange={(event) => patch("pagination", { pageSize: event.target.value as ScreenplaySettings["pagination"]["pageSize"] })}><option>A4</option><option>US Letter</option></select></label><p className="setting-help">Accurate production pagination and page locking remain deliberately disabled until the layout engine can guarantee identical PDF output.</p></>}
          {tab === "Elements" && <><h3>Element formatting</h3><p className="setting-help">The preset architecture is ready. Fine-grained margin and spacing controls remain protected until the pagination engine can validate them safely.</p></>}
          {tab === "Revisions" && <><h3>Revision foundations</h3><label className="check-label"><input type="checkbox" checked={value.revisions.enabled} onChange={(event) => patch("revisions", { enabled: event.target.checked })}/><span>Revision Mode foundation</span></label><p className="setting-help">Revision sets and margin marks will be metadata-driven in the next production milestone.</p></>}
          {(["Production", "Title Page", "Export"] as Tab[]).includes(tab) && <><h3>{tab}</h3><p className="setting-help">This section is reserved in the per-project schema. Controls will be enabled only when their production, title-page, and export engines can preserve the data end to end.</p></>}
        </div>
      </div>
      <footer><button className="secondary" onClick={onClose}>Cancel</button><button className="primary" onClick={() => onSave(value)}>Save screenplay settings</button></footer>
    </section>
  </div>;
}
